import type { Lang } from '../settings/strings';

const ko = {
  brand: 'kasaterm',
  skip: '건너뛰고 터미널 열기',
  language: '언어',
  ko: '한국어',
  en: 'English',
  back: '이전',
  next: '다음',
  retry: '다시 확인',
  loading: '설치 환경을 확인하고 있어요',
  loadingHint: '테마, 터미널 설정, Claude Code와 Codex 로그인을 한 번에 살펴봅니다.',
  loadFailed: '설치 환경을 읽지 못했어요',
  loadFailedHint: 'kasaterm을 다시 열지 않아도 괜찮아요. 여기서 다시 확인할 수 있습니다.',
  actionFailed: '설정을 적용하지 못했어요. 잠시 뒤 다시 시도해 주세요.',
  steps: [
    { short: '외형', title: '익숙한 터미널 모습으로 시작하세요', hint: '기존 설정을 가져오거나 kasaterm의 색과 글꼴을 직접 고릅니다.' },
    { short: 'Agent', title: '이미 로그인한 Agent를 그대로 씁니다', hint: 'Claude Code와 Codex를 감지합니다. 인증정보는 kasaterm에 복사하지 않습니다.' },
    { short: '터미널', title: '새 pane에서 사용할 환경을 확인하세요', hint: '운영체제에 맞는 셸과 가져온 터미널 프로필을 마지막으로 확인합니다.' },
    { short: '완료', title: '준비가 끝났어요', hint: '지금 고른 설정으로 첫 터미널을 엽니다. 나중에 설정에서 모두 바꿀 수 있어요.' },
  ],
  appearance: {
    import: '기존 설정 가져오기',
    manual: '직접 설정',
    importTitle: 'Mac 터미널에서 가져오기',
    importHint: '색상과 글꼴만 읽어 옵니다. 프로필 파일은 바꾸지 않아요.',
    detected: '감지됨',
    unavailable: '가져올 수 없음',
    importAction: '이 설정 가져오기',
    imported: '적용됨',
    importEmpty: '가져올 Apple Terminal 또는 iTerm2 프로필을 찾지 못했어요.',
    importEmptyHint: '직접 설정을 고르면 kasaterm 기본 테마와 설치된 글꼴을 사용할 수 있습니다.',
    theme: '색상 테마',
    themeHint: '앱과 터미널 ANSI 색이 함께 바뀝니다.',
    themeEmpty: '사용할 수 있는 테마가 아직 없어요.',
    accent: '강조색',
    font: '터미널 글꼴',
    fontHint: '설치된 고정폭 글꼴만 표시합니다.',
    fontEmpty: '감지한 고정폭 글꼴이 없어 현재 시스템 글꼴을 유지합니다.',
    fontSize: '글자 크기',
  },
  auth: {
    claude: 'Claude Code',
    codex: 'Codex',
    signedIn: '로그인됨',
    signedOut: '로그인이 필요해요',
    checking: '확인 중…',
    unavailable: '설치되지 않았어요',
    error: '상태를 확인하지 못했어요',
    login: '로그인',
    loginWaiting: '브라우저 로그인 기다리는 중…',
    retry: '다시 감지',
    unavailableHint: '설치한 뒤 설정의 Agent 화면에서 연결할 수 있어요.',
    preferredTitle: '첫 터미널에서 먼저 쓸 Agent',
    preferredHint: '로그인된 항목을 기본으로 골랐어요. 눌러서 바꿀 수 있습니다.',
    preferred: '기본',
    noneReady: '지금 로그인하지 않아도 다음으로 갈 수 있어요.',
    noneReadyHint: '첫 터미널을 연 뒤 설정의 Agent 화면에서 언제든 연결할 수 있습니다.',
    privacy: '로그인은 각 도구의 기존 인증을 사용합니다. kasaterm은 토큰이나 비밀번호를 저장하지 않아요.',
  },
  platform: {
    windowsTitle: 'Windows 기본 셸',
    windowsHint: '새 pane을 열 때 시작할 셸입니다. 감지된 항목을 먼저 보여 줍니다.',
    detected: '설치됨',
    shellEmpty: '감지된 셸이 없어요.',
    shellEmptyHint: '경로를 직접 입력하거나 시스템 기본 셸로 계속할 수 있습니다.',
    customShell: '셸 경로 직접 입력',
    customPlaceholder: 'C:\\Program Files\\PowerShell\\7\\pwsh.exe',
    macTitle: 'Mac 터미널 설정',
    macHint: '가져온 프로필과 현재 kasaterm 외형을 함께 확인합니다.',
    importedFrom: '가져온 곳',
    notImported: 'kasaterm에서 직접 설정',
    currentTheme: '현재 테마',
    currentFont: '현재 글꼴',
    shellTitle: '기본 셸',
    systemDefault: '시스템 기본',
    linuxHint: '시스템 기본 셸로 시작합니다. 나중에 설정에서 경로를 바꿀 수 있어요.',
  },
  ready: {
    appearance: '외형',
    agent: 'Agent',
    terminal: '터미널',
    noAgent: '나중에 연결',
    signedInCount: (count: number) => `${count}개 로그인됨`,
    open: 'kasaterm 열기',
    opening: '첫 터미널 여는 중…',
    restart: '새 글꼴은 kasaterm을 다시 열면 적용돼요.',
    done: '설정이 저장됐어요. kasaterm을 열어도 됩니다.',
    openAgain: 'kasaterm으로 이동',
  },
};

export type OnboardingStrings = typeof ko;

const en: OnboardingStrings = {
  brand: 'kasaterm',
  skip: 'Skip and open terminal',
  language: 'Language',
  ko: '한국어',
  en: 'English',
  back: 'Back',
  next: 'Next',
  retry: 'Check again',
  loading: 'Checking your setup',
  loadingHint: 'Looking at themes, terminal profiles, and existing Claude Code or Codex sign-ins.',
  loadFailed: 'Could not read your setup',
  loadFailedHint: 'You do not need to reopen kasaterm. Try the check again here.',
  actionFailed: 'Could not apply that setting. Try again in a moment.',
  steps: [
    { short: 'Look', title: 'Start with a terminal that feels familiar', hint: 'Bring over an existing profile or choose kasaterm colors and type yourself.' },
    { short: 'Agent', title: 'Keep using the agents already signed in', hint: 'We detect Claude Code and Codex. kasaterm never copies their credentials.' },
    { short: 'Terminal', title: 'Confirm what each new pane will use', hint: 'Review the shell and imported terminal profile for this operating system.' },
    { short: 'Ready', title: 'You are ready', hint: 'Open your first terminal with these choices. Everything stays editable in Settings.' },
  ],
  appearance: {
    import: 'Import existing setup',
    manual: 'Set it myself',
    importTitle: 'Import from a Mac terminal',
    importHint: 'Only colors and type are read. Your source profile is never changed.',
    detected: 'Detected',
    unavailable: 'Unavailable',
    importAction: 'Use this setup',
    imported: 'Applied',
    importEmpty: 'No Apple Terminal or iTerm2 profile was found.',
    importEmptyHint: 'Choose “Set it myself” to use kasaterm themes and installed fonts.',
    theme: 'Color theme',
    themeHint: 'The app chrome and terminal ANSI colors change together.',
    themeEmpty: 'No themes are available yet.',
    accent: 'Accent',
    font: 'Terminal font',
    fontHint: 'Only installed monospace fonts are shown.',
    fontEmpty: 'No monospace font was detected, so the current system font will stay in use.',
    fontSize: 'Text size',
  },
  auth: {
    claude: 'Claude Code',
    codex: 'Codex',
    signedIn: 'Signed in',
    signedOut: 'Sign-in needed',
    checking: 'Checking…',
    unavailable: 'Not installed',
    error: 'Could not check status',
    login: 'Sign in',
    loginWaiting: 'Waiting for browser sign-in…',
    retry: 'Detect again',
    unavailableHint: 'Install it first, then connect it from Agent settings.',
    preferredTitle: 'Agent to use first',
    preferredHint: 'A signed-in agent was picked for you. Select the other one to change it.',
    preferred: 'Default',
    noneReady: 'You can continue without signing in now.',
    noneReadyHint: 'Connect either agent from Agent settings after opening your first terminal.',
    privacy: 'Each tool keeps its own sign-in. kasaterm never stores tokens or passwords.',
  },
  platform: {
    windowsTitle: 'Default Windows shell',
    windowsHint: 'This is what starts in each new pane. Detected choices appear first.',
    detected: 'Installed',
    shellEmpty: 'No shell was detected.',
    shellEmptyHint: 'Enter a path yourself or continue with the system default.',
    customShell: 'Enter a shell path',
    customPlaceholder: 'C:\\Program Files\\PowerShell\\7\\pwsh.exe',
    macTitle: 'Mac terminal setup',
    macHint: 'Review the imported profile alongside the current kasaterm appearance.',
    importedFrom: 'Imported from',
    notImported: 'Set directly in kasaterm',
    currentTheme: 'Current theme',
    currentFont: 'Current font',
    shellTitle: 'Default shell',
    systemDefault: 'System default',
    linuxHint: 'New panes use the system shell. You can enter another path in Settings later.',
  },
  ready: {
    appearance: 'Appearance',
    agent: 'Agent',
    terminal: 'Terminal',
    noAgent: 'Connect later',
    signedInCount: (count: number) => `${count} signed in`,
    open: 'Open kasaterm',
    opening: 'Opening your first terminal…',
    restart: 'The new font takes effect the next time you open kasaterm.',
    done: 'Your setup is saved. kasaterm is ready to open.',
    openAgain: 'Go to kasaterm',
  },
};

export const ONBOARDING_STRINGS: Record<Lang, OnboardingStrings> = { ko, en };
