//! Stamps the build's git revision into KASATERM_GIT_REV at compile
//! time so the running binary can show which build it is (the launch
//! corner banner in main.rs). Falls back to "unknown" outside a git
//! checkout so a tarball build still compiles.
use std::process::Command;

fn main() {
    gen_character_slugs();
    let rev = git_rev().unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=KASATERM_GIT_REV={rev}");
    // Re-stamp when HEAD or the staged index moves so a fresh commit
    // shows the new hash without a clean rebuild. Unstaged edits can't
    // be tracked this way, so the dirty '+' may lag until the next
    // build — acceptable for a launch banner.
    println!("cargo:rerun-if-changed=../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../.git/index");

    // Windows: stamp the app icon into the exe so the taskbar / Start menu /
    // installer use it instead of the generic default. rc.exe (MSVC) does the
    // embed; a missing toolchain just warns rather than failing the build.
    #[cfg(windows)]
    {
        println!("cargo:rerun-if-changed=../../assets/app.ico");
        let mut res = winresource::WindowsResource::new();
        res.set_icon("../../assets/app.ico");
        if let Err(e) = res.compile() {
            println!("cargo:warning=winresource icon embed failed: {e}");
        }
    }
}

/// `characters.json` → `CHARACTER_SLUGS` 표를 생성한다.
///
/// **왜 코드젠인가.** 로스터의 정본은 `characters.json` 인데, 예전엔 이름↔슬러그 표를
/// `theme.rs` 에 손으로 **한 번 더** 적었다. 두 벌이 되면 어긋나고, 어긋나도 컴파일도
/// 실행도 통과한다 — 슬러그는 teammate inbox 파일명이라, 한쪽에만 있는 학생에게 보낸
/// 브리프는 아무도 안 읽는 우편함에 들어가고 보낸 쪽은 성공으로 읽는다. 여기서 만들면
/// 그 두 벌이 존재할 수가 없고, 새 테마는 JSON 하나만 갈아 끼우면 된다.
///
/// 잘못된 로스터는 **빌드가 거부한다**(슬러그 중복·형식 위반·필수 필드 누락). 테마를
/// 만들다 실수하면 화면에서 이상해지기 전에 여기서 걸린다.
fn gen_character_slugs() {
    let json_path = "collab-hooks/characters.json";
    println!("cargo:rerun-if-changed={json_path}");
    let raw = std::fs::read_to_string(json_path)
        .unwrap_or_else(|e| panic!("{json_path} 를 못 읽었다: {e}"));

    // serde 를 build-dependency 로 끌어오지 않으려고 필요한 필드만 훑는다.
    // 형식이 어긋나면(따옴표 안 닫힘 등) 아래 검사에서 개수로 걸린다.
    // header_color 는 slug 다음 줄들에 오므로 마지막 행에 붙인다.
    let mut rows: Vec<(String, String, Option<String>)> = Vec::new();
    let mut name: Option<String> = None;
    for line in raw.lines() {
        let t = line.trim();
        if let Some(v) = field(t, "\"name\":") {
            name = Some(v);
        } else if let Some(slug) = field(t, "\"slug\":") {
            let Some(n) = name.take() else {
                panic!("{json_path}: slug \"{slug}\" 앞에 name 이 없다 — 두 필드는 붙어 있어야 한다");
            };
            rows.push((n, slug, None));
        } else if let Some(color) = field(t, "\"header_color\":") {
            let Some(last) = rows.last_mut() else {
                panic!("{json_path}: header_color \"{color}\" 앞에 name/slug 가 없다");
            };
            if last.2.is_none() {
                last.2 = Some(color);
            }
        }
    }

    // `leader` 는 `leaders[0]` 과 같은 인물을 한 번 더 적어 둔 것이다 — 완전히 같은
    // 쌍은 같은 사람이니 접는다. 이름이나 슬러그 한쪽만 겹치는 것은 아래에서 막는다.
    rows.dedup_by(|a, b| a == b);
    let mut seen = Vec::new();
    rows.retain(|r| {
        if seen.contains(r) {
            return false;
        }
        seen.push(r.clone());
        true
    });

    assert!(!rows.is_empty(), "{json_path}: 캐릭터가 하나도 없다");
    for (n, s, c) in &rows {
        assert!(
            !s.is_empty()
                && s.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_'),
            "{json_path}: \"{n}\" 의 슬러그 \"{s}\" 가 [a-z0-9_] 밖이다 — inbox 파일명이라 \
             한글·대문자·하이픈이 들어가면 조용히 깨진다"
        );
        // 색은 pane 테두리·입력박스·sm테마가 전부 이 표에서 읽는다. 빠지면 그 학생만
        // 테두리 없는 「색 없는 학생」이 되는데 그건 오류가 아니라 화면에서만 어긋난다
        // (실제로 12명 수동 목록 시절 신규 67명이 전부 무색이었다, 2026-08-12) — 빌드가
        // 거부해서 로스터를 만들 때 걸리게 한다.
        let ok = c.as_deref().is_some_and(|c| {
            c.len() == 7
                && c.starts_with('#')
                && c[1..].chars().all(|h| h.is_ascii_hexdigit())
        });
        assert!(ok, "{json_path}: \"{n}\" 의 header_color 가 없거나 #RRGGBB 가 아니다: {c:?}");
    }
    for i in 0..rows.len() {
        for j in (i + 1)..rows.len() {
            assert_ne!(
                rows[i].1, rows[j].1,
                "{json_path}: 슬러그 \"{}\" 가 겹친다({} · {}) — 두 학생이 같은 inbox 를 \
                 쓰게 되고 그건 오류 없이 어긋난다",
                rows[i].1, rows[i].0, rows[j].0
            );
            assert_ne!(
                rows[i].0, rows[j].0,
                "{json_path}: 이름 \"{}\" 가 겹친다 — 화면에서 누가 누군지 사라진다",
                rows[i].0
            );
        }
    }

    let mut out = String::from(
        "// @generated by build.rs from collab-hooks/characters.json — 손으로 고치지 마라.\n\
         pub(crate) const CHARACTER_SLUGS: &[(&str, &str)] = &[\n",
    );
    for (n, s, _) in &rows {
        out.push_str(&format!("    ({n:?}, {s:?}),\n"));
    }
    out.push_str("];\n");
    // 이름 → 고정 accent(0xRRGGBB). theme::character_accent 가 읽는다 — 로스터의
    // header_color 가 정본이고, theme.rs 의 수동 12명 목록은 이 값과 동일했다.
    out.push_str("pub(crate) const CHARACTER_ACCENTS: &[(&str, u32)] = &[\n");
    for (n, _, c) in &rows {
        let hex = &c.as_deref().unwrap()[1..];
        out.push_str(&format!("    ({n:?}, 0x{hex}),\n"));
    }
    out.push_str("];\n");

    let dst = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("character_slugs.rs");
    std::fs::write(&dst, out).unwrap_or_else(|e| panic!("{} 를 못 썼다: {e}", dst.display()));
}

/// `"key": "value",` 한 줄에서 값만 꺼낸다. 값에 `"` 가 들어간 캐릭터는 없다(이름과
/// 슬러그뿐이다) — persona 처럼 긴 문장은 여기서 안 본다.
fn field(line: &str, key: &str) -> Option<String> {
    let rest = line.strip_prefix(key)?.trim();
    let inner = rest.strip_prefix('"')?;
    let end = inner.find('"')?;
    Some(inner[..end].to_string())
}

fn git_rev() -> Option<String> {
    let short = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()?;
    if !short.status.success() {
        return None;
    }
    let mut rev = String::from_utf8(short.stdout).ok()?.trim().to_string();
    if rev.is_empty() {
        return None;
    }
    // Dirty working tree → trailing '+'.
    if let Ok(status) = Command::new("git")
        .args(["status", "--porcelain"])
        .output()
    {
        if status.status.success() && !status.stdout.is_empty() {
            rev.push('+');
        }
    }
    Some(rev)
}
